version: "2"

services:
  certbot:
    build: .
    image: nginx/certbot
    ports:
    - "80:80"
    #- "443:443"
    volumes:
    - ${CERTBOT_CERTS_PATH}:/etc/letsencrypt
    - ${CERTBOT_WEBROOT}:/usr/share/nginx/html
    environment:
    - CERTBOT_HOST
    - CERTBOT_EMAIL
    - CERTBOT_STANDALONE
    - CERTBOT_CERTS_PATH
    - CERTBOT_WEBROOT
    #command: ["nginx", "-g", "daemon off;"]

volumes: 
  www: