version: "2"

services:
  certbot:
    build: certbot
    image: nginx-certbot
    ports:
    - "80:80"
    volumes:
    - ${CERTBOT_CERTS_PATH}:/etc/letsencrypt
    environment:
    - CERTBOT_STANDALONE=true
    - CERTBOT_HOST
    - CERTBOT_EMAIL
    - CERTBOT_CERTS_PATH

volumes: 
  www: